services:
  pos:
    build: .
    restart: unless-stopped
    expose:
      - "8080"
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      BOOTSTRAP_ADMIN_EMAIL: admin@example.com
      BOOTSTRAP_ADMIN_PASSWORD: adminsupervisor
      SESSION_SECURE: "false"
    volumes:
      - ./data:/data

  sqliteweb:
    image: coleifer/sqlite-web:latest
    restart: unless-stopped
    command: sqlite_web -H 0.0.0.0 -p 8080 -x --url-prefix /pardis-db-vault/ /data/pos.db
    volumes:
      - ./data:/data
    expose:
      - "8080"

  caddy:
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - pos
      - sqliteweb

volumes:
  caddy-data:
  caddy-config:
